---
# These tasks install http and the php modules.

- name: Install httpd and php
  package: name={{ item }} state=present
  with_items:
    - "{{ apache_name }}"
    - php
    - "{{ php_mysql }}"

- name: Install web role specific dependencies
  package: name={{ item }} state=present
  with_items:
    - git

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  service: name={{ apache_name }} state=started enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: ansible_os_family == 'RedHat'
  notify: restart apache

- name: Mod PHP to be able to connect to remote database
  command: phpenmod mysqlnd
  when: ansible_os_family == 'Debian'
  notify: restart apache
