---
# This playbook contains common plays that will be run on all nodes.

- name: Include OS-specific variables.
  include_vars: "./vars/{{ ansible_os_family }}.yml"

- name: Install ntp
  package: 
    name="{{ ntp_package }}"
    state=present

- name: Install common dependencies
  package: name={{ item }} state=present update_cache=yes
  with_items:
   - "{{ python3_selinux }}"
   - "{{ python3_semanage }}"
   - firewalld
   - mc

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name={{ ntp_daemon }} state=started enabled=yes
